services: 
  db:
    image: postgres
    
    volumes:
      - postgres_data:/var/lib/postgresql/data

    env_file:
      - ./.env.db

    networks:
      - shared

volumes:
  postgres_data:
    
networks:
  shared: 
    external:
      name: shared