services: 
  db:
    image: postgres
    
    volumes:
      - /data/trading/database/:/var/lib/postgresql/data

    env_file:
      - ./.env.db

    networks:
      - shared
    
networks:
  shared: 
    external:
      name: shared